name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  REGISTRY: "ghcr.io/vannh-glx"
  IMAGE_NAME: "flyte-workflow"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: vannh
          password: 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

      - name: Push image to Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
